### ISSUE TITLE
GRUB_CMDLINE_LINUX not being updated properly in /etc/default/grub

### ISSUE THREAD

**Issue by jrbeilke** [GSA/ansible-os-ubuntu-16#21]
There are multiple tasks attempting to set/update GRUB_CMDLINE_LINUX, but they're using `lineinfile` with a regexp that is generating multiple GRUB_CMDLINE_LINUX lines in /etc/default/grub which are ignored.

On a fresh Ubuntu system the /etc/default/grub file looks something like this:
```
GRUB_CMDLINE_LINUX=""
```

But after running the `ansible-os-ubuntu-16` role we end up with this:
```
GRUB_CMDLINE_LINUX=apparmor="1 security=apparmor"
GRUB_CMDLINE_LINUX="ipv6.disable=1"
GRUB_CMDLINE_LINUX="audit=1"
```

When `update-grub` is run only the last GRUB_CMDLINE_LINUX is used, and the other lines to configure apparmor and disable ipv6 are ignored.

Instead of the following ipv6 task:
```
- name: "3.3.3 | Ensure IPv6 is disabled"
  lineinfile: >
      dest=/etc/default/grub
      line='GRUB_CMDLINE_LINUX="ipv6.disable=1"'
      state=present
      create=yes
  when: ubu16gsa_ipv6_disable == true
  tags:
      - id_3.3.3
```

Something like this instead would allow for updating GRUB_CMDLINE_LINUX without adding another line:
```
- name: "3.3.3 | Ensure IPv6 is disabled"
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(?!.* {{ item.regex }})(.*)"'
    line: 'GRUB_CMDLINE_LINUX="\1 {{ item.context }}"'
    state: present
    backrefs: yes
  with_items:
    - { regex: 'ipv6.disable=', context: 'ipv6.disable=1' }
  notify: [ 'update grub config' ]
  when: ubu16gsa_ipv6_disable == true
  tags:
      - id_3.3.3
```
